export const SET_LANGUAGE = 'SET_LANGUAGE'; //Sets the current language
export const SET_THEME = 'SET_THEME'; //Sets the colour theme
export const SET_BW_MODE = 'SET_BW_MODE'; //Toggles the black-and-white mode
export const SET_CURRENT_TEXT = 'SET_CURRENT_TEXT'; //Sets the currently displayed text
export const SET_NAVBAR_VISIBILITY = 'SET_NAVBAR_VISIBILITY'; //Toggles NavBar visibility
export const SET_DATA_NOTICE_VISIBLE = 'SET_DATA_NOTICE_VISIBLE'; //Toggles the visibility of the data storage notice
export const SET_DATA_NOTICE_ACCEPTED = 'SET_DATA_NOTICE_ACCEPTED'; //Specifies whether the date storage notice was acknowledged by the user
export const SET_PAGE = 'SET_PAGE'; //Specifies which page is currently displayed
export const SET_MAIN_PAGE = 'SET_MAIN_PAGE'; //Specifies whether the main page is currently displayed
export const SET_BOOK_PAGE = 'SET_BOOK_PAGE'; //Specifies whether the Book page is currently displayed
export const SET_BLOG_PAGE = 'SET_BLOG_PAGE'; //Specifies whether the Book page is currently displayed
export const SET_PAGE_RELOAD = 'SET_PAGE_RELOAD'; //Specifies whether the page reloading animation should be played
export const SET_PAGE_LOADED = 'SET_PAGE_LOADED'; //Specifies whether the spinner or the content should be shown