export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_THEME = 'SET_THEME';
export const SET_BW_MODE = 'SET_BW_MODE';
export const SET_CURRENT_TEXT = 'SET_CURRENT_TEXT';
export const SET_NAVBAR_VISIBILITY = 'SET_NAVBAR_VISIBILITY';